version: 1.0

deploy:
  bootstrap:
    excludes:
      - tests
      - node_modules
      - DOCKER_ENV
      - docker_tag
      - output.log
    post-deployment-remote-commands:
      - php bin/console system:install --basic-setup

  recurring:
    excludes:
      - tests
      - node_modules
      - DOCKER_ENV
      - docker_tag
      - output.log
      - var
    pre-deployment-remote-commands:
      - echo "here you could enter maintenance mode..."
    post-deployment-remote-commands:
      - php bin/create-app-secret
      - find $(pwd) -type f -not -path "$(pwd)/logs/*" -exec chmod 664 {} \;
      - find $(pwd) -type d -not -name "logs" -exec chmod 775 {} \;
      - chmod -R o+w var
      - APP_ENV=prod APP_DEBUG=0 php bin/console cache:clear
      - php bin/console assets:install
      - APP_ENV=prod APP_DEBUG=0 php bin/console cache:warmup
