version: 1.0

deploy:
  bootstrap:
    excludes:
      - tests
      - node_modules
      - DOCKER_ENV
      - docker_tag
      - output.log
    post-deployment-remote-commands:
      - php bin/console system:install --basic-setup

  recurring:
    excludes:
      - tests
      - node_modules
      - DOCKER_ENV
      - docker_tag
      - output.log
      - var
    pre-deployment-remote-commands:
      - echo "here you could enter maintenance mode..."
    post-deployment-remote-commands:
      - php bin/console system:generate-jwt-secret
      - php bin/console assets:install
      - php bin/console theme:compile
